//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.19 at 05:03:27 AM SAMT 
//


package ru.volnenko.plugin.arch.mxfile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Defines the geometry (position, size, control points) for a cell.
 * 
 *         For vertices:
 *         - x, y: absolute position of top-left corner (relative to parent)
 *         - width, height: size in pixels
 * 
 *         For edges:
 *         - When relative="1": x is position along edge (0.0=start, 1.0=end,
 *           -1.0=before start), y is perpendicular offset in pixels
 *         - Contains optional mxPoint children for source/target points
 *         - Contains optional Array element with waypoints
 * 
 *         For edge labels (edge cells with relative="1"):
 *         - x: position along edge (-1 to 1, where 0 = center)
 *         - y: perpendicular offset in pixels
 *         - mxPoint with as="offset" for additional pixel offset
 *       
 * 
 * <p>Java class for mxGeometryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mxGeometryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="mxPoint" type="{}mxPointType"/>
 *         &lt;element name="Array" type="{}ArrayType"/>
 *         &lt;element name="mxRectangle" type="{}mxRectangleType"/>
 *       &lt;/choice>
 *       &lt;attribute name="x" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="y" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="height" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="relative" type="{}booleanInt" />
 *       &lt;attribute name="as" type="{http://www.w3.org/2001/XMLSchema}string" fixed="geometry" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mxGeometryType", propOrder = {
    "mxPointOrArrayOrMxRectangle"
})
public class MxGeometryType {

    @XmlElements({
        @XmlElement(name = "mxPoint", type = MxPointType.class),
        @XmlElement(name = "Array", type = ArrayType.class),
        @XmlElement(name = "mxRectangle", type = MxRectangleType.class)
    })
    protected List<Object> mxPointOrArrayOrMxRectangle;
    @XmlAttribute(name = "x")
    protected Double x;
    @XmlAttribute(name = "y")
    protected Double y;
    @XmlAttribute(name = "width")
    protected Double width;
    @XmlAttribute(name = "height")
    protected Double height;
    @XmlAttribute(name = "relative")
    protected String relative;
    @XmlAttribute(name = "as")
    protected String as;

    /**
     * Gets the value of the mxPointOrArrayOrMxRectangle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mxPointOrArrayOrMxRectangle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMxPointOrArrayOrMxRectangle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MxPointType }
     * {@link ArrayType }
     * {@link MxRectangleType }
     * 
     * 
     */
    public List<Object> getMxPointOrArrayOrMxRectangle() {
        if (mxPointOrArrayOrMxRectangle == null) {
            mxPointOrArrayOrMxRectangle = new ArrayList<Object>();
        }
        return this.mxPointOrArrayOrMxRectangle;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setX(Double value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setY(Double value) {
        this.y = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWidth(Double value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHeight(Double value) {
        this.height = value;
    }

    /**
     * Gets the value of the relative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelative() {
        return relative;
    }

    /**
     * Sets the value of the relative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelative(String value) {
        this.relative = value;
    }

    /**
     * Gets the value of the as property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAs() {
        if (as == null) {
            return "geometry";
        } else {
            return as;
        }
    }

    /**
     * Sets the value of the as property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAs(String value) {
        this.as = value;
    }

}
