//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.19 at 05:03:27 AM SAMT 
//


package ru.volnenko.plugin.arch.mxfile;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The graph model containing all cells (shapes, edges, layers) and
 *         canvas configuration. The dx/dy attributes control the scroll offset,
 *         while pageWidth/pageHeight define the page dimensions.
 *       
 * 
 * <p>Java class for mxGraphModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mxGraphModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="root" type="{}rootType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dx" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="dy" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="pageWidth" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="850" />
 *       &lt;attribute name="pageHeight" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="1100" />
 *       &lt;attribute name="pageScale" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *       &lt;attribute name="grid" type="{}booleanInt" default="1" />
 *       &lt;attribute name="gridSize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" default="10" />
 *       &lt;attribute name="guides" type="{}booleanInt" default="1" />
 *       &lt;attribute name="tooltips" type="{}booleanInt" default="1" />
 *       &lt;attribute name="connect" type="{}booleanInt" default="1" />
 *       &lt;attribute name="arrows" type="{}booleanInt" default="1" />
 *       &lt;attribute name="fold" type="{}booleanInt" default="1" />
 *       &lt;attribute name="page" type="{}booleanInt" default="1" />
 *       &lt;attribute name="math" type="{}booleanInt" default="0" />
 *       &lt;attribute name="shadow" type="{}booleanInt" default="0" />
 *       &lt;attribute name="background" type="{}colorType" />
 *       &lt;attribute name="backgroundImage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="adaptiveColors" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mxGraphModelType", propOrder = {
    "root"
})
public class MxGraphModelType {

    @XmlElement(required = true)
    protected RootType root;
    @XmlAttribute(name = "dx")
    protected Double dx;
    @XmlAttribute(name = "dy")
    protected Double dy;
    @XmlAttribute(name = "pageWidth")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger pageWidth;
    @XmlAttribute(name = "pageHeight")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger pageHeight;
    @XmlAttribute(name = "pageScale")
    protected Double pageScale;
    @XmlAttribute(name = "grid")
    protected String grid;
    @XmlAttribute(name = "gridSize")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger gridSize;
    @XmlAttribute(name = "guides")
    protected String guides;
    @XmlAttribute(name = "tooltips")
    protected String tooltips;
    @XmlAttribute(name = "connect")
    protected String connect;
    @XmlAttribute(name = "arrows")
    protected String arrows;
    @XmlAttribute(name = "fold")
    protected String fold;
    @XmlAttribute(name = "page")
    protected String page;
    @XmlAttribute(name = "math")
    protected String math;
    @XmlAttribute(name = "shadow")
    protected String shadow;
    @XmlAttribute(name = "background")
    protected String background;
    @XmlAttribute(name = "backgroundImage")
    protected String backgroundImage;
    @XmlAttribute(name = "adaptiveColors")
    protected String adaptiveColors;

    /**
     * Gets the value of the root property.
     * 
     * @return
     *     possible object is
     *     {@link RootType }
     *     
     */
    public RootType getRoot() {
        return root;
    }

    /**
     * Sets the value of the root property.
     * 
     * @param value
     *     allowed object is
     *     {@link RootType }
     *     
     */
    public void setRoot(RootType value) {
        this.root = value;
    }

    /**
     * Gets the value of the dx property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDx() {
        return dx;
    }

    /**
     * Sets the value of the dx property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDx(Double value) {
        this.dx = value;
    }

    /**
     * Gets the value of the dy property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDy() {
        return dy;
    }

    /**
     * Sets the value of the dy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDy(Double value) {
        this.dy = value;
    }

    /**
     * Gets the value of the pageWidth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPageWidth() {
        if (pageWidth == null) {
            return new BigInteger("850");
        } else {
            return pageWidth;
        }
    }

    /**
     * Sets the value of the pageWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPageWidth(BigInteger value) {
        this.pageWidth = value;
    }

    /**
     * Gets the value of the pageHeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPageHeight() {
        if (pageHeight == null) {
            return new BigInteger("1100");
        } else {
            return pageHeight;
        }
    }

    /**
     * Sets the value of the pageHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPageHeight(BigInteger value) {
        this.pageHeight = value;
    }

    /**
     * Gets the value of the pageScale property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getPageScale() {
        if (pageScale == null) {
            return  1.0D;
        } else {
            return pageScale;
        }
    }

    /**
     * Sets the value of the pageScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPageScale(Double value) {
        this.pageScale = value;
    }

    /**
     * Gets the value of the grid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrid() {
        if (grid == null) {
            return "1";
        } else {
            return grid;
        }
    }

    /**
     * Sets the value of the grid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrid(String value) {
        this.grid = value;
    }

    /**
     * Gets the value of the gridSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGridSize() {
        if (gridSize == null) {
            return new BigInteger("10");
        } else {
            return gridSize;
        }
    }

    /**
     * Sets the value of the gridSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGridSize(BigInteger value) {
        this.gridSize = value;
    }

    /**
     * Gets the value of the guides property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuides() {
        if (guides == null) {
            return "1";
        } else {
            return guides;
        }
    }

    /**
     * Sets the value of the guides property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuides(String value) {
        this.guides = value;
    }

    /**
     * Gets the value of the tooltips property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTooltips() {
        if (tooltips == null) {
            return "1";
        } else {
            return tooltips;
        }
    }

    /**
     * Sets the value of the tooltips property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTooltips(String value) {
        this.tooltips = value;
    }

    /**
     * Gets the value of the connect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnect() {
        if (connect == null) {
            return "1";
        } else {
            return connect;
        }
    }

    /**
     * Sets the value of the connect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnect(String value) {
        this.connect = value;
    }

    /**
     * Gets the value of the arrows property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrows() {
        if (arrows == null) {
            return "1";
        } else {
            return arrows;
        }
    }

    /**
     * Sets the value of the arrows property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrows(String value) {
        this.arrows = value;
    }

    /**
     * Gets the value of the fold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFold() {
        if (fold == null) {
            return "1";
        } else {
            return fold;
        }
    }

    /**
     * Sets the value of the fold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFold(String value) {
        this.fold = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPage() {
        if (page == null) {
            return "1";
        } else {
            return page;
        }
    }

    /**
     * Sets the value of the page property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPage(String value) {
        this.page = value;
    }

    /**
     * Gets the value of the math property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMath() {
        if (math == null) {
            return "0";
        } else {
            return math;
        }
    }

    /**
     * Sets the value of the math property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMath(String value) {
        this.math = value;
    }

    /**
     * Gets the value of the shadow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShadow() {
        if (shadow == null) {
            return "0";
        } else {
            return shadow;
        }
    }

    /**
     * Sets the value of the shadow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShadow(String value) {
        this.shadow = value;
    }

    /**
     * Gets the value of the background property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackground() {
        return background;
    }

    /**
     * Sets the value of the background property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackground(String value) {
        this.background = value;
    }

    /**
     * Gets the value of the backgroundImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundImage() {
        return backgroundImage;
    }

    /**
     * Sets the value of the backgroundImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundImage(String value) {
        this.backgroundImage = value;
    }

    /**
     * Gets the value of the adaptiveColors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdaptiveColors() {
        return adaptiveColors;
    }

    /**
     * Sets the value of the adaptiveColors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdaptiveColors(String value) {
        this.adaptiveColors = value;
    }

}
