//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.19 at 05:03:27 AM SAMT 
//


package ru.volnenko.plugin.arch.mxfile;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mxPointAsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="mxPointAsType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="sourcePoint"/>
 *     &lt;enumeration value="targetPoint"/>
 *     &lt;enumeration value="offset"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "mxPointAsType")
@XmlEnum
public enum MxPointAsType {

    @XmlEnumValue("sourcePoint")
    SOURCE_POINT("sourcePoint"),
    @XmlEnumValue("targetPoint")
    TARGET_POINT("targetPoint"),
    @XmlEnumValue("offset")
    OFFSET("offset");
    private final String value;

    MxPointAsType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MxPointAsType fromValue(String v) {
        for (MxPointAsType c: MxPointAsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
