//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.24 at 01:27:37 PM SAMT 
//


package ru.volnenko.plugin.arch.mxfile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.volnenko.plugin.arch.mxfile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mxfile_QNAME = new QName("", "mxfile");
    private final static QName _RootTypeMxCell_QNAME = new QName("", "mxCell");
    private final static QName _RootTypeUserObject_QNAME = new QName("", "UserObject");
    private final static QName _RootTypeObject_QNAME = new QName("", "object");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.volnenko.plugin.arch.mxfile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MxfileType }
     * 
     */
    public MxfileType createMxfileType() {
        return new MxfileType();
    }

    /**
     * Create an instance of {@link MxGeometryType }
     * 
     */
    public MxGeometryType createMxGeometryType() {
        return new MxGeometryType();
    }

    /**
     * Create an instance of {@link MxRectangleType }
     * 
     */
    public MxRectangleType createMxRectangleType() {
        return new MxRectangleType();
    }

    /**
     * Create an instance of {@link MxCellType }
     * 
     */
    public MxCellType createMxCellType() {
        return new MxCellType();
    }

    /**
     * Create an instance of {@link ArrayType }
     * 
     */
    public ArrayType createArrayType() {
        return new ArrayType();
    }

    /**
     * Create an instance of {@link RootType }
     * 
     */
    public RootType createRootType() {
        return new RootType();
    }

    /**
     * Create an instance of {@link UserObjectType }
     * 
     */
    public UserObjectType createUserObjectType() {
        return new UserObjectType();
    }

    /**
     * Create an instance of {@link DiagramType }
     * 
     */
    public DiagramType createDiagramType() {
        return new DiagramType();
    }

    /**
     * Create an instance of {@link MxGraphModelType }
     * 
     */
    public MxGraphModelType createMxGraphModelType() {
        return new MxGraphModelType();
    }

    /**
     * Create an instance of {@link MxPointType }
     * 
     */
    public MxPointType createMxPointType() {
        return new MxPointType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MxfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mxfile")
    public JAXBElement<MxfileType> createMxfile(MxfileType value) {
        return new JAXBElement<MxfileType>(_Mxfile_QNAME, MxfileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MxCellType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mxCell", scope = RootType.class)
    public JAXBElement<MxCellType> createRootTypeMxCell(MxCellType value) {
        return new JAXBElement<MxCellType>(_RootTypeMxCell_QNAME, MxCellType.class, RootType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserObject", scope = RootType.class)
    public JAXBElement<UserObjectType> createRootTypeUserObject(UserObjectType value) {
        return new JAXBElement<UserObjectType>(_RootTypeUserObject_QNAME, UserObjectType.class, RootType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "object", scope = RootType.class)
    public JAXBElement<UserObjectType> createRootTypeObject(UserObjectType value) {
        return new JAXBElement<UserObjectType>(_RootTypeObject_QNAME, UserObjectType.class, RootType.class, value);
    }

}
