//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.24 at 08:37:34 PM SAMT 
//


package ru.volnenko.plugin.arch.mxfile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Container for all cells in the diagram. Must contain at least two
 *         structural mxCell elements:
 *         1. Root container: id="0", no parent attribute
 *         2. Default layer: id="1", parent="0"
 * 
 *         All visible diagram elements (shapes, edges) must have parent="1"
 *         (or the id of another layer/group).
 * 
 *         Additional layers can be added as mxCell elements with parent="0".
 *         Elements can be wrapped in UserObject/object for custom metadata.
 *       
 * 
 * <p>Java class for rootType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rootType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="mxCell" type="{}mxCellType"/>
 *           &lt;element name="UserObject" type="{}UserObjectType"/>
 *           &lt;element name="object" type="{}UserObjectType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rootType", propOrder = {
    "mxCellOrUserObjectOrObject"
})
public class RootType {

    @XmlElementRefs({
        @XmlElementRef(name = "UserObject", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "object", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "mxCell", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> mxCellOrUserObjectOrObject;

    /**
     * Gets the value of the mxCellOrUserObjectOrObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mxCellOrUserObjectOrObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMxCellOrUserObjectOrObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link UserObjectType }{@code >}
     * {@link JAXBElement }{@code <}{@link UserObjectType }{@code >}
     * {@link JAXBElement }{@code <}{@link MxCellType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getMxCellOrUserObjectOrObject() {
        if (mxCellOrUserObjectOrObject == null) {
            mxCellOrUserObjectOrObject = new ArrayList<JAXBElement<?>>();
        }
        return this.mxCellOrUserObjectOrObject;
    }

}
