@startuml
!include base-library.puml
!include context-view-include.puml
left to right direction
skinparam nodesep 50
skinparam ranksep 100
CONTEXT_VIEW()

Rel(UserAdmin, UserManagerService, "Управление пользователями.")
Rel(UserUsual, TaskManagerService, "Управление задачами.")
Rel_L(TaskManagerService, UserManagerService, "Авторизация пользователей.")

@enduml
