Person(UserUsual, "Пользователь", "", "", $tags = "")

Person(UserAdmin, "Администратор", "", "", $tags = "")

Container(TaskManagerService, "Сервис управления задачами и проектами", "", "task-manager-service", $tags = "selected")

Container(UserManagerService, "Сервис управления пользователями и ролями", "", "user-manager-service", $tags = "selected")

