Person(UserUsual, "Пользователь", "", "", "")

Person(UserAdmin, "Администратор", "", "", "")

Boundary(VolnenkoEnvironment, "volnenko") { 
	Boundary(ClusterEnvironment, "cluster") { 
		Container(TaskManagerService, "Сервис управления задачами и проектами", "", "task-manager-service", "")
	}
}

Boundary(VolnenkoEnvironment, "volnenko") { 
	Boundary(ClusterEnvironment, "cluster") { 
		Container(UserManagerService, "Сервис управления пользователями и ролями", "", "user-manager-service", "")
	}
}

