Person(UserUsual, "Пользователь", "", "", $tags = "")

Person(UserAdmin, "Администратор", "", "", $tags = "")

Container(UserManagerService, "user-manager-service", "Java 21, Spring Boot 3", "mesh", $tags = "selected")

Container(TaskManagerService, "task-manager-service", "Java 21, Spring Boot 3", "mesh", $tags = "selected")

ContainerDb(TaskManagerDatabase, "task_manager", "", "Postgresql 17 Pro (Enterprise)", $tags = "selected")

ContainerQueue(UserCrudTopic, "userCrudTopic", "Apache Kafka, default", "", $tags = "")

ContainerQueue(TaskCrudTopic, "taskCrudTopic", "Apache Kafka, default", "", $tags = "selected")

Container_Ext(NlbHA, "nlbha", "haproxy", "", $tags = "")

Rel(UserUsual, NlbHA, "https")
Rel(UserAdmin, NlbHA, "https")
Rel(UserManagerService, UserCrudTopic, "tcp")
Rel(TaskManagerService, UserManagerService, "http")
Rel(TaskManagerService, TaskManagerDatabase, "tcp")
Rel(TaskManagerService, TaskCrudTopic, "tcp")
Rel(NlbHA, TaskManagerService, "http")
