Person(UserUsual, "Пользователь", "", "", $tags = "")

Person(UserAdmin, "Администратор", "", "", $tags = "")

Boundary(VolnenkoEnvironment, "volnenko") { 
	Boundary(ClusterEnvironment, "cluster") { 
		Container(TaskManagerService, "task-manager-service", "", "", $tags = "selected")
	}
}

Boundary(VolnenkoEnvironment, "volnenko") { 
	Boundary(ClusterEnvironment, "cluster") { 
		Container(UserManagerService, "user-manager-service", "", "", $tags = "")
	}
}

Boundary(VolnenkoEnvironment, "volnenko") { 
	Boundary(ClusterEnvironment, "cluster") { 
		ContainerDb(TaskManagerDatabase, "task_manager", "", "", $tags = "selected")
	}
}

Boundary(VolnenkoEnvironment, "volnenko") { 
	Container_Ext(NlbHA, "nlbha", "", "", $tags = "")
}

Rel(UserUsual, NlbHA, "https")
Rel(UserAdmin, NlbHA, "https")
Rel(TaskManagerService, UserManagerService, "http")
Rel(TaskManagerService, TaskManagerDatabase, "tcp")
