Person(UserUsual, "Пользователь", "", "", "")

Person(UserAdmin, "Администратор", "", "", "")

Boundary(VolnenkoEnvironment, "volnenko") { 
	Boundary(ClusterEnvironment, "cluster") { 
		Container(TaskManagerService, "task-manager-service", "", "", "")
	}
}

Boundary(VolnenkoEnvironment, "volnenko") { 
	Boundary(ClusterEnvironment, "cluster") { 
		Container(UserManagerService, "user-manager-service", "", "", "selected")
	}
}

Boundary(VolnenkoEnvironment, "volnenko") { 
	Boundary(ClusterEnvironment, "cluster") { 
		ContainerDb_Ext(TaskManagerDatabase, "task_manager", "", "", "")
	}
}

Boundary(VolnenkoEnvironment, "volnenko") { 
	Container(NlbHA, "nlbha", "", "", "selected")
}

